#ifndef _PLATFORM_CONFIG_H_
#define _PLATFORM_CONFIG_H_

#include <CCPlatformConfig.h>

#if CC_TARGET_PLATFORM == CC_PLATFORM_MAC
	#define PLATFORM_MAC
#elif CC_TARGET_PLATFORM == CC_PLATFORM_IOS
	#define PLATFORM_IOS
#elif CC_TARGET_PLATFORM == CC_PLATFORM_ANDROID
	#define PLATFORM_ANDROID
#elif CC_TARGET_PLATFORM == CC_PLATFORM_WIN32
	#define PLATFORM_WIN32
#elif CC_TARGET_PLATFORM == CC_PLATFORM_WP8 || CC_TARGET_PLATFORM == CC_PLATFORM_WINRT
	#define PLATFORM_WIN32
#elif CC_TARGET_PLATFORM == CC_PLATFORM_LINUX
	#define PLATFORM_LINUX
#endif

#endif